### ISSUE TITLE
kernel.bin not found

### ISSUE THREAD

**Issue by Mastergamer433** [nanobyte-dev/nanobyte_os#12]
this is so confusing.
It works fine on a VM, but when i try to flash the image to a usb stick with dd and boot on physical hardware i get 
```
Loading...
KERNEL.BIN file not found!
```
and when i mount the usb stick i find both test.txt and kernel.bin on there so i dont understand why it dont find the file.

**Comment by Andrej123456789** [comment]
Can you ask on Discord server instead of spamming issues on Github

**Comment by Mastergamer433** [comment]
Yes i can. I didnt now there was a discord server.

**Comment by chibicitiberiu** [comment]
TBH, I never tried running it from an USB drive on real hardware. Hard to know exactly what the problem is without doing some debugging, but my biggest suspect is the INT 13h, AH 02h function which I've seen to not work properly on large disks. Also, if you hardcode the "cylinders, heads, sectors" instead of using AH 08h = read drive parameters, this could happen.

The best solution in this case would be to add support for reading with [INT 13h, AH 42h](https://en.wikipedia.org/wiki/INT_13H#INT_13h_AH=42h:_Extended_Read_Sectors_From_Drive). I do this in [this livestream](https://www.youtube.com/watch?v=xAxkBJM3amA).
