### ISSUE TITLE
Tar extracts files properly, then hangs - PART - 7

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [nanobyte-dev/nanobyte_os#53]
During the "make toolchain" part of initial setup, Tar hangs after extracting binutils and gcc. In the case of binutils, it succeeds after a while and continues with the setup, but this does not happen when extracting gcc. 

I am running Visual Studio Code in Windows 11 Home using a wsl ubuntu terminal.

**Comment by theOneTrueFunniBoi** [comment]
nvm, it fixed itself

**Comment by funniman-exe** [comment]
A whole year later, this bug reappears.
On the `binutils` end, it just seems to be a really long delay for whatever reason, maybe `tar` is talking a long time to decompress the archive?

`gcc` appears to have the same issue, however the down time is significantly longer, likely because it has a lot more to decompress. I suspect this longer down time for `gcc` is what confused me over a year ago into thinking something went wrong.
